nibbiers store/buyedinn/urls.py
from django.urls import path, include
from buyedinn import views

app_name = "buyedinn"

urlpatterns = [
    # home
    path("", views.index, name="index"),
    path("sign-up/", views.register_view, name="sign-up"),
    path("sign-in/", views.login_view, name="sign-in"),
    path("sign-out/", views.logout_view, name="sign-out"),

    # product
    path("products/", views.product_list_view, name="product-list"),
    path("product/<pid>/", views.product_detail_view, name="product-detail"),

    # category
    path("category/", views.category_list_view, name="category-list"),
    path("category/<cid>/", views.category_product_list_view, name="category-product-list"),

    # vendor
    path("vendors/", views.vendor_list_view, name="vendor-list"),
    path("vendor/<vid>/", views.vendor_detail_view, name="vendor-detail"),

    # search
    path("search/", views.search_view, name="search"),

    # filter Product URL
    path("filter-products", views.filter_product, name="filter-product"),

    # add to cart URL
    path("add-to-cart/", views.add_to_cart, name="add-to-cart"),

    # Cart Page URL
    path("cart/", views.cart_view, name="cart"),

    # Delete Item from Cart
    path("delete-from-cart/", views.delete_item_from_cart, name="delete-from-cart"),

    # Update Item from Cart
    path("update-cart/", views.update_cart, name="update-cart"),

    # Checkout URL
    path("checkout/", views.checkout_view, name="checkout"),

    # Paypal Getway
    path('paypal/', include('paypal.standard.ipn.urls')),

    # payment successful
    path("payment-completed", views.payment_completed_view, name="payment-completed"),

    # payment failed
    path("payment-failed", views.payment_failed_view, name="payment-failed"),

    # Dashboard URL
    path("dashboard/", views.customer_dashboard, name="dashboard"),

    # Order Detail URL
    path("dashboard/order/<int:id>", views.order_detail, name="order-detail"),

    # Making address default
    path("make-default-address/", views.make_address_default, name="make-default-address"),

    # Making address default
    path("profile/update/", views.profile_update, name="profile-update")

]

nibbiers store/ecomproject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("buyedinn.urls")),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nibbiers store/templates/userauths/profile-edit.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content%}
    <main class="main pages">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Pages <span></span> My Account
                </div>
            </div>
        </div>
        <div class="page-content pt-150 pb-150">
            <div class="container">
                <div class="row">
                    <div class="col-lg-10 m-auto">
                        <div class="row">
                            <div class="col-md-3">
                                <div class="dashboard-menu">
                                    <ul class="nav flex-column" role="tablist">
                                        <li class="nav-item">
                                            <a class="nav-link active" id="dashboard-tab" data-bs-toggle="tab" href="#dashboard" role="tab" aria-controls="dashboard" aria-selected="false"><i class="fi-rs-user-sliders mr-10"></i>Profile</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="page-login.html"><i class="fi-rs-sign-out mr-10"></i>Logout</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-md-9">
                                <div class="tab-content account dashboard-content pl-50">
                                    <div class="tab-pane fade active show" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                                        <div class="card">
                                            <div class="card-header border-bottom">
                                                <h3 class="mb-0">Update Profile</h3>
                                            </div>
                                            {% if form.errors %}
                                            <div class="alert-danger alert">
                                                <strong>{{ form.errors }}</strong>
                                            </div>
                                            {% endif %}
                                            <div class="card-body mb-2" style="display: flex; align-items: center; gap: 10px;">
                                                <div>
                                                    {% if profile.image %}
                                                    <span><img src="{{ profile.image.url }}" style="width: 150px; object-fit: cover; border-radius: 50%; height: 150px;" alt=""></span>
                                                    {% else %}
                                                    <span><img src="https://i.stack.imgur.com/YQu5k.png" alt=""></span>
                                                    {% endif %}
                                                </div>
                                                <div>
                                                    <div>
                                                    <form action="" method="POST" enctype="multipart/form-data">
                                                        {% csrf_token %}
                                                        <div class="mb-3">
                                                            {{ form.full_name }}
                                                        </div>
                                                        <div class="mb-3">
                                                            {{ form.bio }}
                                                        </div>
                                                        <div class="mb-3">
                                                            {{ form.phone }}
                                                        </div>
                                                        <div class="mb-3">
                                                            {{ form.image }}
                                                        </div>

                                                        <button href="{% url 'buyedinn:dashboard' %}" class="btn btn-success" type="submit">Save Changes</button>
                                                     </form>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content%}

nibbiers store/templates/userauths/sign-in.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content%}
<main class="main pages">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Pages <span></span> My Account
                </div>
            </div>
        </div>
        <div class="page-content pt-150 pb-150">
            <div class="container">
                <div class="row">
                    <div class="col-xl-8 col-lg-10 col-md-12 m-auto">
                        <div class="row">
                            <div class="col-lg-6 pr-30 d-none d-lg-block">
                                <img class="border-radius-15" src="{% static 'assets/imgs/page/login-1.png' %}" alt="" />
                            </div>
                            <div class="col-lg-6 col-md-8">
                                <div class="login_wrap widget-taber-content background-white">
                                    <div class="padding_eight_all bg-white">
                                        <div class="heading_s1">
                                            <h1 class="mb-5">Login</h1>
                                            <p class="mb-30">Don't have an account? <a href="{% url 'buyedinn:sign-up' %}">Create here</a></p>
                                        </div>
                                        <form method="POST">
                                            {% csrf_token %}
                                            <div class="form-group">
                                                <input type="text" required name="email" placeholder="Username or Email *" />
                                            </div>
                                            <div class="form-group">
                                                <input required type="password" name="password" placeholder="Your password *" />
                                            </div>


                                            <div class="form-group">
                                                <button type="submit" class="btn btn-heading btn-block hover-up" name="login">Log in</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

{% endblock content%}

nibbiers store/templates/userauths/sign-up.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content%}
 <main class="main pages">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Pages <span></span> My Account
                </div>
            </div>
        </div>
        <div class="page-content pt-150 pb-150">
            <div class="container">
                <div class="row">
                    <div class="col-xl-8 col-lg-10 col-md-12 m-auto">
                        <div class="row">
                            <div class="col-lg-6 pr-30 d-none d-lg-block">
                                <img class="border-radius-15" src="{% static 'assets/imgs/page/login-1.png' %}" alt="" />
                            </div>
                            <div class="col-lg-6 col-md-8">
                                <div class="login_wrap widget-taber-content background-white">
                                    <div class="padding_eight_all bg-white">
                                        {% if form.errors %}
                                        <div class="alert alert-danger">
                                            <strong>{{form.errors}}</strong>
                                        </div>
                                        {% endif %}


                                        <div class="heading_s1">
                                            <h1 class="mb-5">Create an Account</h1>
                                            <p class="mb-30">Already have an account? <a href="{% url 'buyedinn:sign-in' %}">Login</a></p>
                                        </div>
                                        <form method="post">
                                            {% csrf_token %}
                                            <div class="form-group">
                                             {{form.username}}
                                            </div>
                                            <div class="form-group">
                                             {{form.email}}
                                            </div>
                                            <div class="form-group">
                                             {{form.password1}}
                                            </div>
                                            <div class="form-group">
                                             {{form.password2}}
                                            </div>
                                            <div class="form-group">
                                                <button type="submit" class="btn btn-heading btn-block hover-up" name="login">Submit &amp; Register</button>
                                            </div>
                                            
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

{% endblock content%}