nibbiers store/buyedinn/urls.py
from django.urls import path, include
from buyedinn import views

app_name = "buyedinn"

urlpatterns = [
    # home
    path("", views.index, name="index"),
    path("sign-up/", views.register_view, name="sign-up"),
    path("sign-in/", views.login_view, name="sign-in"),
    path("sign-out/", views.logout_view, name="sign-out"),

    # product
    path("products/", views.product_list_view, name="product-list"),
    path("product/<pid>/", views.product_detail_view, name="product-detail"),

    # category
    path("category/", views.category_list_view, name="category-list"),
    path("category/<cid>/", views.category_product_list_view, name="category-product-list"),

    # vendor
    path("vendors/", views.vendor_list_view, name="vendor-list"),
    path("vendor/<vid>/", views.vendor_detail_view, name="vendor-detail"),

    # search
    path("search/", views.search_view, name="search"),

    # filter Product URL
    path("filter-products", views.filter_product, name="filter-product"),

    # add to cart URL
    path("add-to-cart/", views.add_to_cart, name="add-to-cart"),

    # Cart Page URL
    path("cart/", views.cart_view, name="cart"),

    # Delete Item from Cart
    path("delete-from-cart/", views.delete_item_from_cart, name="delete-from-cart"),

    # Update Item from Cart
    path("update-cart/", views.update_cart, name="update-cart"),

    # Checkout URL
    path("checkout/", views.checkout_view, name="checkout"),

    # Paypal Getway
    path('paypal/', include('paypal.standard.ipn.urls')),

    # payment successful
    path("payment-completed", views.payment_completed_view, name="payment-completed"),

    # payment failed
    path("payment-failed", views.payment_failed_view, name="payment-failed"),

    # Dashboard URL
    path("dashboard/", views.customer_dashboard, name="dashboard"),

    # Order Detail URL
    path("dashboard/order/<int:id>", views.order_detail, name="order-detail"),

    # Making address default
    path("make-default-address/", views.make_address_default, name="make-default-address"),

    # Making address default
    path("profile/update/", views.profile_update, name="profile-update")

]

nibbiers store/ecomproject/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("buyedinn.urls")),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nibbiers store/templates/core/cart.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content%}

    <main class="main" id="cart-list">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Shop
                    <span></span> Cart
                </div>
            </div>
        </div>
        <div class="container mb-80 mt-50">
            <div class="row">
                <div class="col-lg-8 mb-40">
                    <h1 class="heading-2 mb-10">Your Cart</h1>
                    <div class="d-flex justify-content-between">
                        <h6 class="text-body">There are <span class="text-brand">{{ totalcartitems }}</span> products in your cart</h6>
                        <h6 class="text-body"><a href="#" class="text-muted"><i class="fi-rs-trash mr-5"></i>Clear Cart</a></h6>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8">
                    <div class="table-responsive shopping-summery">
                        <table class="table table-wishlist">
                            <thead>
                                <tr class="main-heading">
                                    <th class="custome-checkbox start pl-30">
                                        <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox11" value="">
                                        <label class="form-check-label" for="exampleCheckbox11"></label>
                                    </th>
                                    <th scope="col">Product</th>
                                    <th scope="col">Title</th>
                                    <th scope="col">Unit Price</th>
                                    <th scope="col" class="text-center">Quantity</th>
                                    <th scope="col">Subtotal</th>
                                    <th scope="col" class="">Refresh</th>
                                    <th scope="col" class="end">Remove</th>

                                </tr>
                            </thead>
                            <tbody>
                                {% for product_id, item in cart_data.items %}
                                <tr class="pt-30">
                                    <td class="custome-checkbox pl-30">
                                        <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox1" value="">
                                        <label class="form-check-label" for="exampleCheckbox1"></label>
                                    </td>
                                    <td class="image product-thumbnail pt-40"><img src="{{ item.image }}" alt="#"></td>
                                    <td class="product-des product-name">
                                        <h6 class="mb-5"><a class="product-name mb-10 text-heading" href="{% url 'buyedinn:product-detail' item.pid %}">{{ item.title }}</a></h6>

                                    </td>
                                    <td class="price" data-title="Price">
                                        <h4 class="text-body">{{ item.price|floatformat:2}} </h4>
                                    </td>
                                    <td class="text-center detail-info" data-title="Stock">
                                        <div class="detail-extralink mr-15">
                                           <input type="text" placeholder="Qty" class="w-25 product-qty-{{ product_id }}" name="" id="" value="{{ item.qty }}" >
                                        </div>
                                    </td>
                                    <td class="price" data-title="Price">
                                        <h4 class="text-brand">${% widthratio item.price 1 item.qty %} </h4>
                                    </td>
<!--                                    <td class="action text-center" data-title="Refresh"><a href="#" class="text-body"><i class="fi-rs-refresh"></i></a></td>-->
                                    <td class="action text-center" data-title="Remove"><button style="border: none; background: none" class="text-body update-product" data-product="{{ product_id }}"><i class="fi-rs-refresh"></i></button></td>
                                    <td class="action text-center" data-title="Remove"><button style="border: none; background: none" class="text-body delete-product" data-product="{{ product_id }}"><i class="fi-rs-trash"></i></button></td>

                                </tr>
                                {% endfor%}

                            </tbody>
                        </table>
                    </div>
                    <div class="divider-2 mb-30"></div>
                    <div class="cart-action d-flex justify-content-between">
                        <a class="btn "><i class="fi-rs-arrow-left mr-10"></i>Continue Shopping</a>
                        <a class="btn  mr-10 mb-sm-15"><i class="fi-rs-refresh mr-10"></i>Update Cart</a>
                    </div>
                    
                </div>
                <div class="col-lg-4">
                    <div class="border p-md-4 cart-totals ml-30">
                        <div class="table-responsive">
                            <table class="table no-border">
                                <tbody>
                                    <tr>
                                        <td class="cart_total_label">
                                            <h6 class="text-muted">Subtotal</h6>
                                        </td>
                                        <td class="cart_total_amount">
                                            <h4 class="text-brand text-end">${{cart_total_amount|floatformat:2}}</h4>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td scope="col" colspan="2">
                                            <div class="divider-2 mt-10 mb-10"></div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="cart_total_label">
                                            <h6 class="text-muted">Shipping</h6>
                                        </td>
                                        <td class="cart_total_amount">
                                            <h4 class="text-heading text-end">Free</h4>
                                        </td>
                                    </tr>

                                    <tr>
                                        <td scope="col" colspan="2">
                                            <div class="divider-2 mt-10 mb-10"></div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="cart_total_label">
                                            <h6 class="text-muted">Total</h6>
                                        </td>
                                        <td class="cart_total_amount">
                                            <h4 class="text-brand text-end">${{cart_total_amount|floatformat:2}}</h4>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        {% if totalcartitems %}
                        <a href="{% url 'buyedinn:checkout' %}" class="btn mb-20 w-100">Proceed To CheckOut<i class="fi-rs-sign-out ml-15"></i></a>
                        {% endif %}                    </div>
                </div>
            </div>
        </div>
    </main>

{% endblock content%}

nibbiers store/templates/core/category-list.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content%}
    <main class="main">
        <div class="page-header mt-30 mb-75">
            <div class="container">
                <div class="archive-header">
                    <div class="row align-items-center">
                        <div class="col-xl-3">
                            <h1 class="mb-15">Categories</h1>
                            <div class="breadcrumb">
                                <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                                <span></span> Categories
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <div class="page-content mb-50">
            <div class="container">
                <div class="row">
                    <div class="col-lg-9">
                        <div class="shop-product-fillter mb-50 pr-30">
                            <div class="total-product">
                                <h2>
                                    
                                    {{categories.count}} Categories
                                </h2>
                            </div>
                            <div class="sort-by-product-area">
                                <div class="sort-by-cover mr-10">
                                    <div class="sort-by-product-wrap">
                                        <div class="sort-by">
                                            <span><i class="fi-rs-apps"></i>Show:</span>
                                        </div>
                                        <div class="sort-by-dropdown-wrap">
                                            <span> 50 <i class="fi-rs-angle-small-down"></i></span>
                                        </div>
                                    </div>
                                    <div class="sort-by-dropdown">
                                        <ul>
                                            <li><a class="active" href="#">50</a></li>
                                            <li><a href="#">100</a></li>
                                            <li><a href="#">150</a></li>
                                            <li><a href="#">200</a></li>
                                            <li><a href="#">All</a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="sort-by-cover">
                                    <div class="sort-by-product-wrap">
                                        <div class="sort-by">
                                            <span><i class="fi-rs-apps-sort"></i>Sort:</span>
                                        </div>
                                        <div class="sort-by-dropdown-wrap">
                                            <span>Featured <i class="fi-rs-angle-small-down"></i></span>
                                        </div>
                                    </div>
                                    <div class="sort-by-dropdown">
                                        <ul>
                                            <li><a class="active" href="#">Featured</a></li>
                                            <li><a href="#">Newest</a></li>
                                            <li><a href="#">Most comments</a></li>
                                            <li><a href="#">Release Date</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="loop-grid pr-30">
                            <div class="row">
                                {% for c in categories %}
                                <article class="col-xl-4 col-lg-6 col-md-6 text-center hover-up mb-30 animated">
                                    <div class="post-thumb">
                                        <a href="{% url 'buyedinn:category-product-list' c.cid%}">
                                            <img class="border-radius-15" src="{{c.image.url}}" alt="" />
                                        </a>
                                        <div class="entry-meta">
                                            <a class="entry-meta meta-2" href="blog-category-grid.html"><i class="fi-rs-heart"></i></a>
                                        </div>
                                    </div>
                                    <div class="entry-content-2">
                                        
                                        <h4 class="post-title mb-15">
                                            <a href="{% url 'buyedinn:category-product-list' c.cid %}">{{ c.title }}</a>
                                        </h4>
                                        <div class="entry-meta font-xs color-grey mt-10 pb-10">
                                            <div>

                                                <span class="hit-count has-dot mr-10">{{c.category.count}} Product{{c.category.count|pluralize}}</span>

                                            </div>
                                        </div>
                                    </div>
                                </article>
                                {% endfor%}
                            </div>
                        </div>
                        <div class="pagination-area mt-15 mb-sm-5 mb-lg-0">
                            <nav aria-label="Page navigation example">
                                <ul class="pagination justify-content-start">
                                    <li class="page-item">
                                        <a class="page-link" href="#"><i class="fi-rs-arrow-small-left"></i></a>
                                    </li>
                                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                                    <li class="page-item active"><a class="page-link" href="#">2</a></li>
                                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                                    <li class="page-item"><a class="page-link dot" href="#">...</a></li>
                                    <li class="page-item"><a class="page-link" href="#">6</a></li>
                                    <li class="page-item">
                                        <a class="page-link" href="#"><i class="fi-rs-arrow-small-right"></i></a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                    <div class="col-lg-3 primary-sidebar sticky-sidebar">
                        <div class="widget-area">
                            <div class="sidebar-widget-2 widget_search mb-50">
                                <div class="search-form">
                                    
                                </div>
                            </div>
                            
                           
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

{% endblock content%}

nibbiers store/templates/core/index.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content%}
    <main class="main">
        <section class="home-slider position-relative mb-30" ;>
            <div class="home-slide-cover">
                <div class="hero-slider-1 style-4 dot-style-1 dot-style-1-position-1" style="height: 800px">
                    <div class="single-hero-slider rectangle single-animation-wrap"  style="background-image: url({% static 'assets/imgs/slider/slide-1.png' %}) ; height: 800px">
                        
                    </div>
                    <div class="single-hero-slider rectangle single-animation-wrap" style="background-image: url({% static 'assets/imgs/slider/slide-2.png' %}); height: 800px ">
                    </div>
                </div>
                <div class="slider-arrow hero-slider-1-arrow"></div>
            </div>
        </section>
        <!--End hero-->
        <div class="container mb-30">
            <div class="row">
                <div class="col-lg-4-5">
                    <section class="product-tabs section-padding position-relative">
                        
                        <!--End nav-tabs-->
                        <div class="tab-content" id="myTabContent">
                            <div class="tab-pane fade show active" id="tab-one" role="tabpanel" aria-labelledby="tab-one">
                                <div class="row product-grid-4">
                                    {% for p in products %}
                                    <div class="col-lg-1-5 col-md-4 col-12 col-sm-6">
                                        <div class="product-cart-wrap mb-30">
                                            <div class="product-img-action-wrap">
                                                <div class="product-img product-img-zoom">
                                                    <a href="{% url 'buyedinn:product-detail' p.pid %}">
                                                        <img class="default-img" src="{{ p.image.url }}" alt="" />
                                                        <img class="hover-img" src="{{ p.image.url }}" alt="" />
                                                    </a>
                                                </div>
                                                
                                                <div class="product-badges product-badges-position product-badges-mrg">
                                                    <span class="hot">-{{ p.get_percentage|floatformat:0}}%</span>
                                                </div>
                                            </div>
                                            <div class="product-content-wrap">
                                                <div class="product-category">
                                                    <a href="{% url 'buyedinn:product-detail' p.pid %}">{{ p.category.title}}</a>
                                                </div>
                                                <h2><a href="{% url 'buyedinn:product-detail' p.pid %}">{{ p.title }}</a></h2>
                                                <div class="product-rate-cover">
                                                    <div class="product-rate d-inline-block">
                                                        <div class="product-rating" style="width: 90%"></div>
                                                    </div>
                                                    <span class="font-small ml-5 text-muted"> (4.0)</span>
                                                </div>
                                                <div>
                                                    <span class="font-small text-muted">By <a href="vendor-details-1.html">{{ p.vendor.title}}</a></span>
                                                </div>
                                                <div class="product-card-bottom">
                                                    <div class="product-price">
                                                      <span>$</span> <span class="current-product-price-{{p.id}}">{{ p.price }}</span>
                                                        <span class="old-price">{{ p.old_price }}</span>
                                                    </div>
                                                    <div class="add-cart">
                                                        <input type="hidden" value="1" id="product-quantity" class="product-quantity-{{ p.id }}">
                                                        <input type="hidden" class="product-pid-{{ p.id }}" value="{{ p.pid }}">
                                                        <input type="hidden" class="product-image-{{ p.id }}" value="{{ p.image.url }}">
                                                        <input type="hidden" class="product-id-{{ p.id }}"  value="{{ p.pid }}">
                                                        <input type="hidden" class="product-title-{{ p.id }}" value="{{ p.title }}">

                                                        <button class="add add-to-cart-btn" data-index="{{p.id}}" style="border:none;" id="add-to-cart-btn" ><i class="fi-rs-shopping-cart mr-5"></i>Add </button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                    <!--end product card-->

                                </div>
                                <!--End product-grid-4-->
                            </div>
                           
                        </div>
                        <!--End tab-content-->
                    </section>
                    
                </div>
               
            </div>
        </div>
       
        
    </main>


{% endblock content%}

nibbiers store/templates/core/payment-completed.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content%}

    <div class="invoice invoice-content invoice-5">
        <div class="back-top-home hover-up mt-30 ml-30">
          
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="invoice-inner">
                        <div class="invoice-info" id="invoice_wrapper">
                            <div class="invoice-header">
                                <div class="logo logo-width-1">
                                    <a href="{% url 'buyedinn:index' %}"><img src="{% static 'assets/imgs/theme/logo.png' %}" alt="logo" /></a>
                                </div>
                            </div>
                            <div class="invoice-banner">
                                <img src="{% static '{% static ' %}'assets/imgs/invoice/banner.png' %}" alt="">
                            </div>
                            <div class="invoice-center">
                                <div class="table-responsive">
                                    <table class="table table-striped invoice-table">
                                        <thead class="bg-active">
                                            <tr>
                                                <th>Item Item</th>
                                                <th class="text-center">Unit Price</th>
                                                <th class="text-center">Quantity</th>
                                                <th class="text-right">Amount</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for product_id, item in cart_data.items %}
                                            <tr>
                                                <td>
                                                    <div class="item-desc-1">
                                                        <span>{{item.title}}</span>
                                                    </div>
                                                </td>
                                                <td class="text-center">${{item.price}}</td>
                                                <td class="text-center">{{item.qty}}</td>
                                                <td class="text-right">${% widthratio item.price 1 item.qty %}</td>
                                            </tr>
                                            {% endfor %}

                                            <tr>
                                                <td colspan="3" class="text-end f-w-600">SubTotal</td>
                                                <td class="text-right">${{cart_total_amount}}</td>
                                            </tr>
<!--                                            <tr>-->
<!--                                                <td colspan="3" class="text-end f-w-600">Tax</td>-->
<!--                                                <td class="text-right">$85.99</td>-->
<!--                                            </tr>-->
                                            <tr>
                                                <td colspan="3" class="text-end f-w-600">Grand Total</td>
                                                <td class="text-right f-w-600">${{cart_total_amount}}</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="invoice-bottom pb-80">
                                <div class="row">
                                    <div class="col-md-6">
                                        <h6 class="mb-15">Invoice Infor</h6>
                                        <p class="font-sm">

                                            <strong>Invoice To: </strong>{{request.user|title}}<br />

                                        </p>
                                    </div>
                                    <div class="col-md-6 text-end">
                                        <h6 class="mb-15">Total Amount</h6>
                                        <h3 class="mt-0 mb-0 text-brand">${{cart_total_amount}}</h3>
                                        <p class="mb-0 text-muted">Taxes Included</p>
                                    </div>
                                </div>
                                <div class="row text-center">
                                    <div class="hr mt-30 mb-30"></div>
                                    <p class="mb-0 text-muted"><strong>Note:</strong>This is computer generated receipt and does not require physical signature.</p>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content%}